# สำหรับ Development (ใช้ SQLite3 ในเครื่องพัฒนา)
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

# สำหรับ Test (ใช้ SQLite3 เช่นเดียวกับใน development)
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

# สำหรับ Production (ใช้ PostgreSQL บน Render)
production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5
  timeout: 5000

# สำหรับ Cucumber (ใช้ฐานข้อมูลแบบเดียวกับ Test)
cucumber:
  <<: *test
